name: Greet User

on:
  workflow_dispatch:  # Only runs manually
    inputs:
      username:
        description: 'Enter your name'
        required: true  # Making it required to ensure input is provided
        default: 'Guest'

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Get Current Date & Time
        id: datetime
        run: echo "datetime=$(date)" >> $GITHUB_ENV

      - name: Greet User
        run: echo "Hello, ${{ github.event.inputs.username }}! The current date and time is ${{ env.datetime }}"
